### ISSUE TITLE
Can't get it working...

### ISSUE THREAD

**Issue by nicksav** [CXuesong/BotBuilder.Standard#2]
Hey, I am not able to get this working.
![image](https://user-images.githubusercontent.com/9266365/31478375-481a7212-af53-11e7-8467-a829cb73e1c2.png)
Any clue?

Thanks
Nick

**Comment by CXuesong** [comment]
It seems that I should have reload the whole solution after changing the package names… Sad story…

I have rebuilt the packages and released [v3.11.0](https://github.com/CXuesong/BotBuilder.Standard/releases/tag/ported3.11.0). Hope it solves the problem.

**Comment by nicksav** [comment]
Hi Chen!

Are you open for a join opportunities? We need to build a bot and I am
looking for good developer to help me out.


2017-10-13 0:11 GMT+10:00 Chen <notifications@github.com>:

**Comment by CXuesong** [comment]
HI Nick,


I've sent the reply to your e-mail address used in regular git commits. Perhaps we could had a private conversation there…




At 2017-10-13 06:22:12, "NIck" <notifications@github.com> wrote:
Hi Chen!

Are you open for a join opportunities? We need to build a bot and I am
looking for good developer to help me out.


2017-10-13 0:11 GMT+10:00 Chen <notifications@github.com>:
