### ISSUE TITLE
PromptDialog.Confirm loop in .NET Core 2.0

### ISSUE THREAD

**Issue by mastermaq** [CXuesong/BotBuilder.Standard#6]
## Bot Info 
* App ID: 
* SDK Platform: **.NET Framework & .NET Core**
* SDK Version: **3.12.2.4 (.NET Framework) and 3.12.2.5 (.NET Core)**
* Active Channels: **Bot Emulator**
* Deployment Environment: **Bot Emulator**

## Issue Description
I have the same code inside a .NET Framework 4.6.1 Web API project referencing the latest official Microsoft.Bot.* packages and a .NET Core 2.0 Web API project referencing the latest CXuesong.Ported.Microsoft.Bot.* packages. The root dialog is a LUIS dialog and what I am trying to do is respond with a confirm prompt in the None intent. This works as expected in the .NET Framework version, but results in a loop in the .NET Core version, where responding to the prompt results in another prompt.

## Code Example
In the MessagesController:

```csharp
if (activity != null && activity.GetActivityType() == ActivityTypes.Message)
{
    await Conversation.SendAsync(activity, () => new BasicLuisDialog());                
}
else
{
    HandleSystemMessage(activity);
}
return new HttpResponseMessage(System.Net.HttpStatusCode.Accepted);
```

In the BasicLuisDialog:

```csharp
[LuisIntent("None")]
public async Task NoneIntent(IDialogContext context, LuisResult result)
{
    PromptDialog.Confirm(context, AfterAskInvestigate, "Would you like us to investigate and follow-up?");
}

private async Task AfterAskInvestigate(IDialogContext context, IAwaitable<bool> result)
{
    var investigate = await result;

    if (investigate)
        await context.PostAsync("OK, we're on the case.");
    else
        await context.PostAsync("No problem, we'll leave it.");

    context.Wait(MessageReceived);
}
```

## Reproduction Steps
1. Fire up the bot emulator and send it a message that matches the None intent.
2. A confirm prompt is sent back to the user.
3. Click on either Yes or No.

## Expected Behavior
After responding to the confirm prompt, the ResumeAfter function should execute.

## Actual Results
This works as expected in the .NET Framework version, but in .NET Core 2.0 any response to the confirm prompt is treated like a new conversation and you are presented with the prompt again - the ResumeAfter function never executes.

**Comment by CXuesong** [comment]
Did you see any exceptions bubbled up in the Output window of your VS debugger/activity log? Seems that Bot Builder resets the conversation if unhandled exceptions occurs.

**Comment by CXuesong** [comment]
I've created a simple project containing your code, and it works well.
* [Project](https://github.com/CXuesong/BotBuilderPlayground.Standard/tree/BotBuilder.Standard%236)
* [Your code](https://github.com/CXuesong/BotBuilderPlayground.Standard/blob/bdeb13e42a68635dbdfc8901c61d88fdf17be188/BotBuilderPlayground/Dialogs/RootDialog.cs#L27)

My suggestion is
* try the `PromptDialog` in a class without LUIS in your project, and see whether it works.
* as I've mentioned, note if there is any exception shown in the Output window when you see abnormal behavior

**Comment by mastermaq** [comment]
Thank you for putting that together! That helped me figure out the issue. I don't remember why now, but I had the following in my Startup class (probably a copy/paste from [one of the official samples](https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-GlobalMessageHandlers/README.md)):

```csharp
public Startup(IConfiguration configuration)
{
    Configuration = configuration;

    RegisterBotModules();
}

private void RegisterBotModules()
{
    Conversation.UpdateContainer(builder =>
    {
        builder.RegisterModule(new ReflectionSurrogateModule());
    });
}
```

That registermodule line with the ReflectionSurrogateModule appears to be the culprit. If I comment out that code, it works just fine.

This is the exception thrown when the abnormal behavior occurs:

> Exception on deserializing stored data! Stack has been cleared. Details: System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Bot.Builder.Internals.Fibers.Serialization.StoreInstanceByFieldsSurrogate.System.Runtime.Serialization.ISerializationSurrogate.SetObjectData(Object obj, SerializationInfo info, StreamingContext context, ISurrogateSelector selector)
>    at Microsoft.Bot.Builder.Internals.Fibers.Serialization.SurrogateLogDecorator.System.Runtime.Serialization.ISerializationSurrogate.SetObjectData(Object obj, SerializationInfo info, StreamingContext context, ISurrogateSelector selector)
>    at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
>    at System.Runtime.Serialization.ObjectManager.DoFixups()
>    at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
>    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
>    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
>    at Microsoft.Bot.Builder.Internals.Fibers.FormatterStore`1.Microsoft.Bot.Builder.Internals.Fibers.IStore<T>.TryLoad(T& item)
>    at Microsoft.Bot.Builder.Internals.Fibers.ErrorResilientStore`1.Microsoft.Bot.Builder.Internals.Fibers.IStore<T>.TryLoad(T& item)

Thanks!

**Comment by CXuesong** [comment]
Yes, the source of problem is `StoreInstanceByFieldsSurrogate` registered in `ReflectionSurrogateModule `, which is used to make non-serializable types "serializable" by persisting and restoring their fields.

The problem is, In .NET Core, `RuntimeType` is not serializable, and `BinaryFormatter` will try to use it to deserialize it. But as I have mentioned in dotnet/corefx#23785, `BinaryFormatter` in .NET Core does not support resolving this `Type` instace of `RuntimeType` very well, so I used my `TypeSerializationSurrogate` implementation to handle this.

When serializing your objects, `TypeSerializationSurrogate` almost has the lowest negative priority, while `StoreInstanceByFieldsSurrogate` has the priority of 2, so it will take precedence to my `TypeSerializationSurrogate`.
https://github.com/CXuesong/BotBuilder.Standard/blob/f035889ecd3f4e3f39dab734ee68c817abe7cc22/CSharp/Library/Microsoft.Bot.Builder.Autofac/Fibers/FiberModule.cs#L196-L199

Thus, my suggestion is that you not take any shortcuts, but make your classes serializable, so that the use of `StoreInstanceByFieldsSurrogate` can be removed. If, still, you want to use this class, then copy the code above, and reduce the priority to a number greater than `10 - int.MaxValue`.

**Comment by mastermaq** [comment]
Thank you!
